// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin_stats.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countOrders = `-- name: CountOrders :one
SELECT COUNT(*)::BIGINT
FROM orders
`

func (q *Queries) CountOrders(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countOrders)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countUsageLogs = `-- name: CountUsageLogs :one
SELECT COUNT(*)::BIGINT
FROM usage_logs
`

func (q *Queries) CountUsageLogs(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsageLogs)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*)::BIGINT
FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const listDailyUsageStats = `-- name: ListDailyUsageStats :many
SELECT
    DATE(created_at) AS date,
    COUNT(*)::BIGINT AS total_count,
    COUNT(*) FILTER (WHERE success = true)::BIGINT AS success_count,
    COALESCE(SUM(cost_cents), 0)::BIGINT AS total_cost_cents
FROM usage_logs
GROUP BY DATE(created_at)
ORDER BY date DESC
`

type ListDailyUsageStatsRow struct {
	Date           pgtype.Date
	TotalCount     int64
	SuccessCount   int64
	TotalCostCents int64
}

func (q *Queries) ListDailyUsageStats(ctx context.Context) ([]ListDailyUsageStatsRow, error) {
	rows, err := q.db.Query(ctx, listDailyUsageStats)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDailyUsageStatsRow
	for rows.Next() {
		var i ListDailyUsageStatsRow
		if err := rows.Scan(
			&i.Date,
			&i.TotalCount,
			&i.SuccessCount,
			&i.TotalCostCents,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listModelUsageStats = `-- name: ListModelUsageStats :many
SELECT
    model,
    COUNT(*)::BIGINT AS total_count,
    COUNT(*) FILTER (WHERE success = true)::BIGINT AS success_count,
    COALESCE(SUM(cost_cents), 0)::BIGINT AS total_cost_cents
FROM usage_logs
GROUP BY model
ORDER BY total_count DESC
`

type ListModelUsageStatsRow struct {
	Model          string
	TotalCount     int64
	SuccessCount   int64
	TotalCostCents int64
}

func (q *Queries) ListModelUsageStats(ctx context.Context) ([]ListModelUsageStatsRow, error) {
	rows, err := q.db.Query(ctx, listModelUsageStats)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListModelUsageStatsRow
	for rows.Next() {
		var i ListModelUsageStatsRow
		if err := rows.Scan(
			&i.Model,
			&i.TotalCount,
			&i.SuccessCount,
			&i.TotalCostCents,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserUsageStats = `-- name: ListUserUsageStats :many
SELECT
    user_id,
    COUNT(*)::BIGINT AS total_count,
    COUNT(*) FILTER (WHERE success = true)::BIGINT AS success_count,
    COALESCE(SUM(cost_cents), 0)::BIGINT AS total_cost_cents
FROM usage_logs
GROUP BY user_id
ORDER BY total_cost_cents DESC
`

type ListUserUsageStatsRow struct {
	UserID         int64
	TotalCount     int64
	SuccessCount   int64
	TotalCostCents int64
}

func (q *Queries) ListUserUsageStats(ctx context.Context) ([]ListUserUsageStatsRow, error) {
	rows, err := q.db.Query(ctx, listUserUsageStats)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserUsageStatsRow
	for rows.Next() {
		var i ListUserUsageStatsRow
		if err := rows.Scan(
			&i.UserID,
			&i.TotalCount,
			&i.SuccessCount,
			&i.TotalCostCents,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumPaidOrderAmount = `-- name: SumPaidOrderAmount :one
SELECT COALESCE(SUM(amount_cents), 0)::BIGINT
FROM orders
WHERE status = 'paid'
`

func (q *Queries) SumPaidOrderAmount(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, sumPaidOrderAmount)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const sumUsageCost = `-- name: SumUsageCost :one
SELECT COALESCE(SUM(cost_cents), 0)::BIGINT
FROM usage_logs
WHERE success = true
`

func (q *Queries) SumUsageCost(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, sumUsageCost)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}
