// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: balance_transactions.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBalanceTransaction = `-- name: CreateBalanceTransaction :one
INSERT INTO balance_transactions (
    user_id,
    type,
    amount_cents,
    balance_before_cents,
    balance_after_cents,
    order_id,
    usage_log_id,
    remark
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, user_id, type, amount_cents, balance_before_cents, balance_after_cents, order_id, usage_log_id, remark, created_at
`

type CreateBalanceTransactionParams struct {
	UserID             int64
	Type               string
	AmountCents        int64
	BalanceBeforeCents int64
	BalanceAfterCents  int64
	OrderID            pgtype.Int8
	UsageLogID         pgtype.Int8
	Remark             string
}

func (q *Queries) CreateBalanceTransaction(ctx context.Context, arg CreateBalanceTransactionParams) (BalanceTransaction, error) {
	row := q.db.QueryRow(ctx, createBalanceTransaction,
		arg.UserID,
		arg.Type,
		arg.AmountCents,
		arg.BalanceBeforeCents,
		arg.BalanceAfterCents,
		arg.OrderID,
		arg.UsageLogID,
		arg.Remark,
	)
	var i BalanceTransaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.AmountCents,
		&i.BalanceBeforeCents,
		&i.BalanceAfterCents,
		&i.OrderID,
		&i.UsageLogID,
		&i.Remark,
		&i.CreatedAt,
	)
	return i, err
}

const listBalanceTransactionsByUser = `-- name: ListBalanceTransactionsByUser :many
SELECT id, user_id, type, amount_cents, balance_before_cents, balance_after_cents, order_id, usage_log_id, remark, created_at
FROM balance_transactions
WHERE user_id = $1
ORDER BY id DESC
LIMIT $2 OFFSET $3
`

type ListBalanceTransactionsByUserParams struct {
	UserID int64
	Limit  int32
	Offset int32
}

func (q *Queries) ListBalanceTransactionsByUser(ctx context.Context, arg ListBalanceTransactionsByUserParams) ([]BalanceTransaction, error) {
	rows, err := q.db.Query(ctx, listBalanceTransactionsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BalanceTransaction
	for rows.Next() {
		var i BalanceTransaction
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.AmountCents,
			&i.BalanceBeforeCents,
			&i.BalanceAfterCents,
			&i.OrderID,
			&i.UsageLogID,
			&i.Remark,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
