// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID           int64
	Email        string
	PasswordHash string
	Name         string
	Role         string
	Status       string
	BalanceCents int64
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}
