// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: models.sql

package database

import (
	"context"
)

const createModel = `-- name: CreateModel :one
INSERT INTO models (
    name,
    provider,
    input_price_per_1k_cents,
    output_price_per_1k_cents
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, name, provider, input_price_per_1k_cents, output_price_per_1k_cents, status, created_at, updated_at
`

type CreateModelParams struct {
	Name                  string
	Provider              string
	InputPricePer1kCents  int64
	OutputPricePer1kCents int64
}

func (q *Queries) CreateModel(ctx context.Context, arg CreateModelParams) (Model, error) {
	row := q.db.QueryRow(ctx, createModel,
		arg.Name,
		arg.Provider,
		arg.InputPricePer1kCents,
		arg.OutputPricePer1kCents,
	)
	var i Model
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Provider,
		&i.InputPricePer1kCents,
		&i.OutputPricePer1kCents,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveModelByName = `-- name: GetActiveModelByName :one
SELECT id, name, provider, input_price_per_1k_cents, output_price_per_1k_cents, status, created_at, updated_at
FROM models
WHERE name = $1
  AND status = 'active'
`

func (q *Queries) GetActiveModelByName(ctx context.Context, name string) (Model, error) {
	row := q.db.QueryRow(ctx, getActiveModelByName, name)
	var i Model
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Provider,
		&i.InputPricePer1kCents,
		&i.OutputPricePer1kCents,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listModels = `-- name: ListModels :many
SELECT id, name, provider, input_price_per_1k_cents, output_price_per_1k_cents, status, created_at, updated_at
FROM models
ORDER BY id DESC
`

func (q *Queries) ListModels(ctx context.Context) ([]Model, error) {
	rows, err := q.db.Query(ctx, listModels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Model
	for rows.Next() {
		var i Model
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Provider,
			&i.InputPricePer1kCents,
			&i.OutputPricePer1kCents,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateModelStatus = `-- name: UpdateModelStatus :one
UPDATE models
SET status = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, name, provider, input_price_per_1k_cents, output_price_per_1k_cents, status, created_at, updated_at
`

type UpdateModelStatusParams struct {
	ID     int64
	Status string
}

func (q *Queries) UpdateModelStatus(ctx context.Context, arg UpdateModelStatusParams) (Model, error) {
	row := q.db.QueryRow(ctx, updateModelStatus, arg.ID, arg.Status)
	var i Model
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Provider,
		&i.InputPricePer1kCents,
		&i.OutputPricePer1kCents,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
