// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: orders.sql

package database

import (
	"context"
)

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (
    user_id,
    order_no,
    amount_cents
) VALUES (
    $1, $2, $3
)
RETURNING id, user_id, order_no, amount_cents, status, paid_at, created_at, updated_at
`

type CreateOrderParams struct {
	UserID      int64
	OrderNo     string
	AmountCents int64
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder, arg.UserID, arg.OrderNo, arg.AmountCents)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OrderNo,
		&i.AmountCents,
		&i.Status,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrderByID = `-- name: GetOrderByID :one
SELECT id, user_id, order_no, amount_cents, status, paid_at, created_at, updated_at
FROM orders
WHERE id = $1
`

func (q *Queries) GetOrderByID(ctx context.Context, id int64) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByID, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OrderNo,
		&i.AmountCents,
		&i.Status,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOrders = `-- name: ListOrders :many
SELECT id, user_id, order_no, amount_cents, status, paid_at, created_at, updated_at
FROM orders
ORDER BY id DESC
LIMIT $1 OFFSET $2
`

type ListOrdersParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListOrders(ctx context.Context, arg ListOrdersParams) ([]Order, error) {
	rows, err := q.db.Query(ctx, listOrders, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.OrderNo,
			&i.AmountCents,
			&i.Status,
			&i.PaidAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdersByUser = `-- name: ListOrdersByUser :many
SELECT id, user_id, order_no, amount_cents, status, paid_at, created_at, updated_at
FROM orders
WHERE user_id = $1
ORDER BY id DESC
LIMIT $2 OFFSET $3
`

type ListOrdersByUserParams struct {
	UserID int64
	Limit  int32
	Offset int32
}

func (q *Queries) ListOrdersByUser(ctx context.Context, arg ListOrdersByUserParams) ([]Order, error) {
	rows, err := q.db.Query(ctx, listOrdersByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.OrderNo,
			&i.AmountCents,
			&i.Status,
			&i.PaidAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOrderPaid = `-- name: MarkOrderPaid :one
UPDATE orders
SET status = 'paid',
    paid_at = NOW(),
    updated_at = NOW()
WHERE id = $1
  AND status = 'pending'
RETURNING id, user_id, order_no, amount_cents, status, paid_at, created_at, updated_at
`

func (q *Queries) MarkOrderPaid(ctx context.Context, id int64) (Order, error) {
	row := q.db.QueryRow(ctx, markOrderPaid, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OrderNo,
		&i.AmountCents,
		&i.Status,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
