// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: usage_logs.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUsageLog = `-- name: CreateUsageLog :one
INSERT INTO usage_logs (
    user_id,
    api_key_id,
    model,
    endpoint,
    status_code,
    success,
    request_body_bytes,
    response_body_bytes,
    cost_cents
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
RETURNING id, user_id, api_key_id, model, endpoint, status_code, success, request_body_bytes, response_body_bytes, created_at, cost_cents
`

type CreateUsageLogParams struct {
	UserID            int64
	ApiKeyID          pgtype.Int8
	Model             string
	Endpoint          string
	StatusCode        int32
	Success           bool
	RequestBodyBytes  int64
	ResponseBodyBytes int64
	CostCents         int64
}

func (q *Queries) CreateUsageLog(ctx context.Context, arg CreateUsageLogParams) (UsageLog, error) {
	row := q.db.QueryRow(ctx, createUsageLog,
		arg.UserID,
		arg.ApiKeyID,
		arg.Model,
		arg.Endpoint,
		arg.StatusCode,
		arg.Success,
		arg.RequestBodyBytes,
		arg.ResponseBodyBytes,
		arg.CostCents,
	)
	var i UsageLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ApiKeyID,
		&i.Model,
		&i.Endpoint,
		&i.StatusCode,
		&i.Success,
		&i.RequestBodyBytes,
		&i.ResponseBodyBytes,
		&i.CreatedAt,
		&i.CostCents,
	)
	return i, err
}

const listUsageLogsByUser = `-- name: ListUsageLogsByUser :many
SELECT id, user_id, api_key_id, model, endpoint, status_code, success, request_body_bytes, response_body_bytes, created_at, cost_cents
FROM usage_logs
WHERE user_id = $1
ORDER BY id DESC
LIMIT $2 OFFSET $3
`

type ListUsageLogsByUserParams struct {
	UserID int64
	Limit  int32
	Offset int32
}

func (q *Queries) ListUsageLogsByUser(ctx context.Context, arg ListUsageLogsByUserParams) ([]UsageLog, error) {
	rows, err := q.db.Query(ctx, listUsageLogsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UsageLog
	for rows.Next() {
		var i UsageLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ApiKeyID,
			&i.Model,
			&i.Endpoint,
			&i.StatusCode,
			&i.Success,
			&i.RequestBodyBytes,
			&i.ResponseBodyBytes,
			&i.CreatedAt,
			&i.CostCents,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
