// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package database

import (
	"context"
)

const addUserBalance = `-- name: AddUserBalance :one
UPDATE users
SET balance_cents = balance_cents + $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, email, password_hash, name, role, status, balance_cents, created_at, updated_at
`

type AddUserBalanceParams struct {
	ID           int64
	BalanceCents int64
}

func (q *Queries) AddUserBalance(ctx context.Context, arg AddUserBalanceParams) (User, error) {
	row := q.db.QueryRow(ctx, addUserBalance, arg.ID, arg.BalanceCents)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Role,
		&i.Status,
		&i.BalanceCents,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users(
email,password_hash,name) VALUES ($1,$2,$3) RETURNING id, email, password_hash, name, role, status, balance_cents, created_at, updated_at
`

type CreateUserParams struct {
	Email        string
	PasswordHash string
	Name         string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.PasswordHash, arg.Name)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Role,
		&i.Status,
		&i.BalanceCents,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deductUserBalance = `-- name: DeductUserBalance :one
UPDATE users
SET balance_cents = balance_cents - $2,
    updated_at = NOW()
WHERE id = $1
  AND balance_cents >= $2
RETURNING id, email, password_hash, name, role, status, balance_cents, created_at, updated_at
`

type DeductUserBalanceParams struct {
	ID           int64
	BalanceCents int64
}

func (q *Queries) DeductUserBalance(ctx context.Context, arg DeductUserBalanceParams) (User, error) {
	row := q.db.QueryRow(ctx, deductUserBalance, arg.ID, arg.BalanceCents)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Role,
		&i.Status,
		&i.BalanceCents,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, name, role, status, balance_cents, created_at, updated_at FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Role,
		&i.Status,
		&i.BalanceCents,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, name, role, status, balance_cents, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Role,
		&i.Status,
		&i.BalanceCents,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, password_hash, name, role, status, balance_cents, created_at, updated_at
FROM users
ORDER BY id DESC
LIMIT $1 OFFSET $2
`

type ListUsersParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.PasswordHash,
			&i.Name,
			&i.Role,
			&i.Status,
			&i.BalanceCents,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
